data:extend({
  { 
    name="generator",
    type="generator",
    icon="__highfleet-ships__/graphics/icons/lmfao.png",
    icon_size=128,
    fluid_usage_per_tick=1,
    burns_fluid=true,
    scale_fluid_usage=true,
    maximum_temperature=165,
    effectivity=1,
    max_power_output="2MW",
    energy_source={type="electric",usage_priority="primary-output"},
    collision_box={{0,0},{0,0}},
    selection_box={{0,0},{0,0}},
    fluid_box=
    {
      base_area=2,
      height=1,
      base_level=-1,
      pipe_covers=pipecoverspictures(),
      pipe_connections=
      {
        {type="input-output",position={0,0}},
        {type="input-output",position={0,0}}
      },
      production_type="input-output",
    },
    horizontal_animation=
    {
      filename="__highfleet-ships__/graphics/entity/generator/generator-h.png",
      size={256,157}
    },
    vertical_animation=
    {
      filename="__highfleet-ships__/graphics/entity/generator/generator-v.png",
      size={205,256}
    }
  }
})
  