data:extend({--  Recipes
    {-- Copper Catalyst
        name="copper-catalyst",
        type="recipe",
        category="chemistry",
        energy_required=3,
        enabled=true,
        crafting_machine_tint=
        {
            primary={217,171,54},
            secondary={135,86,32},
            tertiary={51,27,0},
            quaternary={186,134,76}
        },
        ingredients=
        {   
            {"copper-ore",10},
            {"plastic-bar",3},
            {type="fluid",name="sulfuric-acid",amount=50}
        },
        results=
        {
            {"copper-catalyst",1}
        }
    },
    {--  Gas Refinery
        name="gas-refinery",
        type="recipe",
        category="crafting",
        energy_required=10,
        enabled=true,
        ingredients=
        {
            {"steel-plate",20},
            {"iron-gear-wheel",15},
            {"advanced-circuit",10},
            {"pipe",10},
            {"concrete",10}
        },
        results=
        {
            {"gas-refinery",1}
        }
    },
    {--  Fractionating Spire
        name="fractionating-spire",
        type="recipe",
        category="crafting",
        energy_required=20,
        enabled=true,
        ingredients=
        {
            {"steel-plate",30},
            {"iron-gear-wheel",25},
            {"processing-unit",5},
            {"pipe",25},
            {"refined-concrete",10}
        },
        results=
        {
            {"fractionating-spire",1}
        }
    },
    {--  Pyrolysis Plant
        name="pyrolysis-plant",
        type="recipe",
        category="crafting",
        energy_required=15,
        enabled=true,
        ingredients=
        {
            {"stone-brick",20},
            {"electric-furnace",5},
            {"processing-unit",10},
            {"plastic-bar",10},
            {"refined-hazard-concrete",10}
        },
        results=
        {
            {"pyrolysis-plant",1}
        }
    },
    {--  Petroleum Gas Refining
        name="petroleum-gas-refining",
        type="recipe",
        category="gas-refining",
        enabled=true,
        order="aa",
        subgroup="fuel-production",
        icon="__highfleet-ships__/graphics/icons/petroleum-gas-refining.png",
        icon_size=128,
        energy_required=15,
        ingredients=
        {
            {type="fluid",name="petroleum-gas",amount=165}
        },
        results=
        {
            {type="fluid",name="crude-fuel",amount=60},
            {type="fluid",name="light-gas",amount=105}
        }
    },
    {--  Crude Fuel Fractionating
        name="crude-fuel-fractionating",
        type="recipe",
        category="gas-fractionating",
        energy_required=25,
        enabled=true,
        order="ab",
        subgroup="fuel-production",
        icon="__highfleet-ships__/graphics/icons/crude-fuel-fractionating.png",
        icon_size=128,
        ingredients=
        {
            {type="fluid",name="crude-fuel",amount=100}
        },
        results=
        {
            {type="fluid",name="refined-fuel",amount=40},
            {type="fluid",name="heavy-gas",amount=60}
        }
    },
    {--  Crude Gas Mixing
        name="crude-gas-mixing",
        type="recipe",
        category="gas-mixing",
        energy_required=75,
        enabled=true,
        order="ad",
        subgroup="fuel-production",
        icon="__highfleet-ships__/graphics/icons/crude-gas-mixing.png",
        icon_size=64,
        main_product="",
        emissions_multiplier=4,
        ingredients=
        {
            {type="fluid",name="crude-fuel",amount=90},
            {type="fluid",name="heavy-gas",amount=60}
        },
        results=
        {
            {type="fluid",name="crude-fuel",amount=120}
        }
    },
    {--  Light Oil Steam Cracking
        name="light-oil-steam-cracking",
        type="recipe",
        category="steam-cracking",
        energy_required=20,
        enabled=true,
        order="ac",
        subgroup="fuel-production",
        icon="__highfleet-ships__/graphics/icons/light-oil-steam-cracking.png",
        icon_size=128,
        ingredients=
        {
            {type="fluid",name="light-oil",amount=130},
            {type="fluid",name="steam",amount=200}
        },
        results=
        {
            {type="fluid",name="refined-fuel",amount=50},
            {type="fluid",name="ethylene-gas",amount=70}
        }
    },
    {--  Advanced Gas Mixing
        name="advanced-gas-mixing",
        type="recipe",
        category="gas-mixing",
        energy_required=30,
        enabled=true,
        order="ae",
        subgroup="fuel-production",
        icon="__highfleet-ships__/graphics/icons/advanced-gas-mixing.png",
        icon_size=64,
        ingredients=
        {
            {type="fluid",name="ethylene-gas",amount=105},
            {type="fluid",name="light-gas",amount=180},
            {"copper-catalyst",6}
        },
        results=
        {
            {type="fluid",name="refined-fuel",amount=75},
            {amount=6,name="copper-catalyst",probability=0.95}
        }
    },
})
